---
# - name: Install Docker on multiple hosts
#   hosts: docker_hosts
#   become: true
  
#   tasks:
#   - name: Update the package cache
#     apt:
#       update_cache: yes

#   - name: Upgrade system packages
#     apt:
#       upgrade: yes

#   - name: Reboot the system
#     reboot:

#   - name: Wait for the system to come back online
#     wait_for_connection:
#       delay: 10

#   - name: Install necessary packages
#     package:
#       name:
#         - apt-transport-https
#         - ca-certificates
#         - curl
#         - software-properties-common
#       state: present

#   - name: Add Docker GPG key
#     shell: curl -fsSL https://download.docker.com/linux/raspbian/gpg | apt-key add -

#   - name: Add Docker repository
#     shell: add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/raspbian $(lsb_release -cs) stable"

#   - name: Update the apt cache
#     apt: update_cache=yes

#   - name: Install Docker.io
#     package:
#       name: docker.io
#       state: present

#   - name: Start and enable Docker service
#     service:
#       name: docker
#       state: started
#       enabled: yes

#   - name: Add user to Docker group
#     user: name={{ ansible_user }} groups=docker append=yes

#   - name: Reboot the system
#     reboot:

#   - name: Wait for the system to come back online
#     wait_for_connection:
#       delay: 10

- name: Install Git and Clone Repository on Raspberry Pi OS
  hosts: docker_hosts
  
  tasks:
  - name: Install Git
    become: yes
    apt:
      name: git
      state: present

  - name: Clone repository
    become_user: "{{ ansible_user }}"
    git:
      repo: https://github.com/evan-aja/lab-jarkom-fe
      dest: "/home/{{ ansible_user }}/lab-jarkom-fe"

- name: Build images for deployment
  hosts: docker_hosts
  become_user: "{{ ansible_user }}"
  
  tasks:
  - name: Run Docker build command
    shell: 
      cmd: "docker build -t lab-jarkom-web:latest . -f scripts/Dockerfile"
      chdir: /home/{{ ansible_user }}/lab-jarkom-fe

- name: Copy file from parent directory to remote machine
  hosts: docker_host

  tasks:
    - name: Copy .env file
      copy:
        src: ../.env
        dest: "/home/{{ ansible_user }}/lab-jarkom-fe"

- name: Apply Kubernetes manifests
  hosts: docker_hosts_master
  become_user: "{{ ansible_user }}"

  tasks:
    - name: Apply manifests
      shell: kubectl apply -f /home/{{ ansible_user }}/lab-jarkom-fe/scripts/Kubernetes/Deployment.yaml